serenity.project.name = DKB Pega API Test
serenity.outputDirectory = target/site/serenity
serenity.requirement.types = feature
serenity.take.screenshots = FOR_FAILURES
serenity.logging = VERBOSE
base.url = https://qzzoaeeb.pegaacademy.net
client.id = 13348118649164335558
client.secret = 631B2F0CA85BDCD8CA8DFA452DED3481
