serenity.project.name = DKB Pega API Test
serenity.outputDirectory = target/site/serenity
serenity.requirement.types = feature
serenity.take.screenshots = FOR_FAILURES
serenity.logging = VERBOSE
base.url = https://6ypri2sq.pegacea.net
client.id = 51055056300759505289
client.secret = F79A0B0ADCB8F49791618B30A774E564
username = TellUsMore_Service
password = pega123!
