serenity.project.name = DKB Pega API Test
serenity.outputDirectory = target/site/serenity
serenity.requirement.types = feature
serenity.take.screenshots = FOR_FAILURES
serenity.logging = VERBOSE
base.url = https://qzzoaeeb.pegaacademy.net
client.id = 51744799296870571382
client.secret = 0C92DBD52770B18266103F6C5C3C96F2
